name: aturnintime
recipe: backdrop
env_file:
  - pull.env
config:
  webroot: web
  via: nginx
  backdrush: 1.x-1.x

services:
  database:
    type: mariadb:10.3

tooling:
  drush:
    cmd: drush --root=/app/web --uri=https://aturnintime.lndo.site
