name: aturnintime
recipe: backdrop
config:
  webroot: web
  backdrush: 1.1.0

services:
  database:
    type: mariadb:10.3

tooling:
  drush:
    cmd: drush --root=/app/web --uri=https://aturnintime.lndo.site
